name: Build iOS IPA

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        cache: true
        
    - name: Flutter doctor
      run: flutter doctor -v
      
    - name: Check project structure
      run: |
        pwd
        ls -la
        echo "Checking if platformnext_vpn directory exists..."
        ls -la platformnext_vpn/
        echo "Checking pubspec.yaml..."
        cat platformnext_vpn/pubspec.yaml
        echo "Checking if this is a Flutter project..."
        flutter --version
      
    - name: Get dependencies
      run: |
        cd platformnext_vpn
        flutter pub get
        flutter pub deps
      
    - name: Generate iOS files
      run: |
        cd platformnext_vpn
        flutter precache --ios
        flutter clean
        flutter pub get
        cd ios
        pod install --repo-update
        cd ..
        # Verify app icons are present
        echo "Checking app icons..."
        ls -la ios/Runner/Assets.xcassets/AppIcon.appiconset/
        flutter build ios --no-codesign --debug
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.4.0'
        
    - name: Skip iOS signing
      run: |
        echo "Skipping iOS signing - building unsigned IPA"
        
    - name: Build iOS app
      run: |
        cd platformnext_vpn
        flutter clean
        flutter pub get
        cd ios
        pod install --repo-update
        cd ..
        flutter build ios --release --no-codesign
        
    - name: Create IPA
      run: |
        cd platformnext_vpn
        echo "Checking build directory structure..."
        find . -name "Runner.app" -type d
        echo "Listing build directory..."
        ls -la build/ios/iphoneos/ || echo "build/ios/iphoneos not found"
        echo "Listing build directory..."
        ls -la build/ios/ || echo "build/ios not found"
        echo "Listing build directory..."
        ls -la build/ || echo "build not found"
        
        # Try different possible paths
        if [ -d "build/ios/iphoneos/Runner.app" ]; then
          echo "Found Runner.app in build/ios/iphoneos/"
          RUNNER_PATH="build/ios/iphoneos/Runner.app"
        elif [ -d "build/ios/Release-iphoneos/Runner.app" ]; then
          echo "Found Runner.app in build/ios/Release-iphoneos/"
          RUNNER_PATH="build/ios/Release-iphoneos/Runner.app"
        elif [ -d "build/ios/Debug-iphoneos/Runner.app" ]; then
          echo "Found Runner.app in build/ios/Debug-iphoneos/"
          RUNNER_PATH="build/ios/Debug-iphoneos/Runner.app"
        else
          echo "Runner.app not found, searching..."
          find . -name "Runner.app" -type d
          exit 1
        fi
        
        # Create IPA structure
        mkdir -p Payload
        cp -r "$RUNNER_PATH" Payload/
        zip -r platformnext_vpn.ipa Payload/
        echo "IPA created successfully!"
          
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: platformnext-vpn-ipa
        path: platformnext_vpn/*.ipa
        retention-days: 30
        
    - name: Build completed
      run: |
        echo "iOS build completed successfully!"
        echo "IPA file is available in the artifacts section"
