name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: Find Flutter project
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Looking for pubspec.yaml..."
        find . -name "pubspec.yaml" -type f
        echo "Looking for Flutter projects..."
        find . -name "pubspec.yaml" -exec dirname {} \;
        
    - name: Get dependencies
      run: |
        # Find the Flutter project directory
        FLUTTER_DIR=$(find . -name "pubspec.yaml" -exec dirname {} \; | head -1)
        if [ -z "$FLUTTER_DIR" ]; then
          echo "No Flutter project found!"
          exit 1
        fi
        echo "Found Flutter project in: $FLUTTER_DIR"
        cd "$FLUTTER_DIR"
        echo "Current directory: $(pwd)"
        echo "Running flutter pub get..."
        flutter pub get
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Prepare iOS build
      run: |
        # Find the Flutter project directory
        FLUTTER_DIR=$(find . -name "pubspec.yaml" -exec dirname {} \; | head -1)
        echo "Using Flutter project in: $FLUTTER_DIR"
        cd "$FLUTTER_DIR/ios"
        pod install --repo-update
        
    - name: Build iOS app
      run: |
        # Find the Flutter project directory
        FLUTTER_DIR=$(find . -name "pubspec.yaml" -exec dirname {} \; | head -1)
        echo "Using Flutter project in: $FLUTTER_DIR"
        cd "$FLUTTER_DIR"
        flutter build ios --release --no-codesign
      
    - name: Create IPA
      run: |
        # Find the Flutter project directory
        FLUTTER_DIR=$(find . -name "pubspec.yaml" -exec dirname {} \; | head -1)
        echo "Using Flutter project in: $FLUTTER_DIR"
        cd "$FLUTTER_DIR/ios"
        xcodebuild -workspace Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath Runner.xcarchive \
          archive
        xcodebuild -exportArchive \
          -archivePath Runner.xcarchive \
          -exportPath . \
          -exportOptionsPlist ExportOptions.plist
          
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: |
          */ios/*.ipa
          ios/*.ipa
