name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build Flutter app
      run: |
        # Find the Flutter project directory
        FLUTTER_DIR=$(find . -name "pubspec.yaml" -exec dirname {} \; | head -1)
        echo "Found Flutter project in: $FLUTTER_DIR"
        cd "$FLUTTER_DIR"
        
        echo "=== Flutter doctor ==="
        flutter doctor
        
        echo "=== Get dependencies ==="
        flutter pub get
        
        echo "=== Build for iOS simulator (no code signing) ==="
        flutter build ios --simulator --release --no-codesign
        
        echo "=== Build completed successfully! ==="
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: flutter-ios-build
        path: |
          */build/ios/
          build/ios/
        retention-days: 7
