name: Build IPA for eSign

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-ipa:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        cache: true
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.4.0'
        
    - name: Get dependencies
      run: |
        cd platformnext_vpn
        flutter pub get
        
    - name: Build iOS app (Release)
      run: |
        cd platformnext_vpn
        echo "Building iOS app for eSign..."
        flutter build ios --no-codesign --release
        echo "Build completed successfully!"
        
    - name: Create unsigned IPA
      run: |
        cd platformnext_vpn/ios
        echo "Creating unsigned IPA for eSign..."
        
        # Create Payload directory
        mkdir -p Payload
        
        # Copy the built app to Payload
        cp -r build/ios/iphoneos/Runner.app Payload/
        
        # Create IPA file
        zip -r platformnext_vpn_unsigned.ipa Payload/
        
        # Show file info
        ls -la *.ipa
        echo "IPA created: platformnext_vpn_unsigned.ipa"
        
    - name: Upload IPA for eSign
      uses: actions/upload-artifact@v4
      with:
        name: platformnext-vpn-unsigned-ipa
        path: platformnext_vpn/ios/platformnext_vpn_unsigned.ipa
        retention-days: 30
        
    - name: Build completed
      run: |
        echo "✅ IPA build completed successfully!"
        echo "📱 Download the IPA from Artifacts section"
        echo "🔐 Use eSign on your phone to sign with personal certificate"
        echo "📲 Install the signed IPA on your device"
