name: Simple Flutter Test

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        cache: true
        
    - name: Check directory structure
      run: |
        echo "Current directory:"
        pwd
        echo "Contents:"
        ls -la
        echo "PlatformNext VPN directory:"
        ls -la platformnext_vpn/
        
    - name: Test Flutter in correct directory
      run: |
        cd platformnext_vpn
        echo "In platformnext_vpn directory:"
        pwd
        echo "Contents:"
        ls -la
        echo "Flutter version:"
        flutter --version
        echo "Getting dependencies:"
        flutter pub get
        echo "Analyzing code:"
        flutter analyze
