name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.0'
        channel: 'stable'
        cache: true
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.4.0'
        
    - name: Build Flutter app
      run: |
        # Find the Flutter project directory
        FLUTTER_DIR=$(find . -name "pubspec.yaml" -exec dirname {} \; | head -1)
        echo "Found Flutter project in: $FLUTTER_DIR"
        cd "$FLUTTER_DIR"
        
        echo "=== Flutter doctor ==="
        flutter doctor
        
        echo "=== Get dependencies ==="
        flutter pub get
        
        echo "=== Build for iOS device (for IPA) ==="
        flutter build ios --release --no-codesign
        
        echo "=== Build completed successfully! ==="
        
    - name: Create IPA file
      run: |
        # Find the Flutter project directory
        FLUTTER_DIR=$(find . -name "pubspec.yaml" -exec dirname {} \; | head -1)
        echo "Creating IPA file in: $FLUTTER_DIR"
        cd "$FLUTTER_DIR/ios"
        
        # Create IPA using xcodebuild (no code signing)
        echo "=== Creating IPA file ==="
        xcodebuild -workspace Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath Runner.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          archive
        
        # Export IPA (without code signing)
        echo "=== Exporting IPA ==="
        xcodebuild -exportArchive \
          -archivePath Runner.xcarchive \
          -exportPath . \
          -exportOptionsPlist ExportOptions.plist \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
        
        echo "=== IPA file created successfully! ==="
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-ipa-build
        path: |
          */ios/*.ipa
          ios/*.ipa
          */build/ios/
          build/ios/
        retention-days: 7
