name: Test Flutter Build

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test-flutter:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        cache: true
        
    - name: Flutter doctor
      run: flutter doctor -v
      
    - name: Check project structure
      run: |
        pwd
        ls -la
        echo "Checking pubspec.yaml..."
        cat pubspec.yaml
        echo "Checking if this is a Flutter project..."
        flutter --version
      
    - name: Get dependencies
      run: flutter pub get
      
    - name: Analyze code
      run: flutter analyze
      
    - name: Run tests
      run: flutter test
