name: Test Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: Debug directory structure
      run: |
        echo "=== Current directory ==="
        pwd
        echo "=== Directory contents ==="
        ls -la
        echo "=== Looking for pubspec.yaml ==="
        find . -name "pubspec.yaml" -type f
        echo "=== Looking for Flutter projects ==="
        find . -name "pubspec.yaml" -exec dirname {} \;
        echo "=== Checking if platformnext_vpn exists ==="
        if [ -d "platformnext_vpn" ]; then
          echo "platformnext_vpn directory found!"
          ls -la platformnext_vpn/
        else
          echo "platformnext_vpn directory not found"
        fi
        
    - name: Test Flutter commands
      run: |
        # Try to find and use the Flutter project
        if [ -f "platformnext_vpn/pubspec.yaml" ]; then
          echo "Found Flutter project in platformnext_vpn/"
          cd platformnext_vpn
          echo "Current directory: $(pwd)"
          echo "Running flutter doctor..."
          flutter doctor
          echo "Running flutter pub get..."
          flutter pub get
        else
          echo "No Flutter project found in platformnext_vpn/"
          echo "Looking for any Flutter project..."
          FLUTTER_DIR=$(find . -name "pubspec.yaml" -exec dirname {} \; | head -1)
          if [ -n "$FLUTTER_DIR" ]; then
            echo "Found Flutter project in: $FLUTTER_DIR"
            cd "$FLUTTER_DIR"
            echo "Current directory: $(pwd)"
            echo "Running flutter doctor..."
            flutter doctor
            echo "Running flutter pub get..."
            flutter pub get
          else
            echo "No Flutter project found anywhere!"
            exit 1
          fi
        fi
