include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Basic rules only
    avoid_print: true
    prefer_single_quotes: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/generated/**"
    - "**/build/**"
    - "**/.dart_tool/**"
    - "**/ios/**"
    - "**/android/**"
    - "**/web/**"
    - "**/windows/**"
    - "**/macos/**"
    - "**/linux/**"